platform :ios, '16.0'

target 'Runner' do
  use_frameworks!
  project '../example/ios/Runner.xcodeproj'

  # Add your dependencies here
  pod 'AmwalPayment', '~> 0.1.1'

  # Add any other dependencies needed for your project

end
